### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by NicoCG** [fals/cqrs-clean-eventual-consistency#1]
Hello,

Any chance you have a example angular or mvc version that points to the api?

**Comment by fals** [comment]
Hi @NicoCG I'm working hard to get it done with both UI approaches. Right now I still not completely satisfied with the Sync application because of my implementation of RabbitMQ. I gonna implement it soon.

**Comment by NicoCG** [comment]
I am excited to hear that. Sorry I am new to RabbitMQ is it similar to Docker?

**Comment by fals** [comment]
@Basic UI was added, but still working in progress
