### ISSUE TITLE
Blazor removal

### ISSUE THREAD

**Issue by michaeljosiah** [fals/cqrs-clean-eventual-consistency#4]
Hi, any reason you removed Blazor from the solution?

**Comment by fals** [comment]
@michaeljosiah the way I implemented it sharing the model between Api and Blazor was quite hacky. I'm going to add it back with the updated version and better enginieering.

**Comment by michaeljosiah** [comment]
Thanks for the response. Out of interest what is hacky about it. I like the idea of sharing the API model between the API and Blazor. My thinking is that there is a service layer within Blazor that translates the API models back to a model used specifically within Blazor. So just like we convert the API models on the server back to Command and Query objects, on the client, we translate the Blazor API models back to their own Blazor service models. What are your thoughts or do you have a better approach in mind.

**Comment by fals** [comment]
@michaeljosiah Sharing those contracts prevent client and service to evolve independently. Sometimes duplication for good is needed.
