### ISSUE TITLE
Error when creating card

### ISSUE THREAD

**Issue by jamalkaksouri** [fals/cqrs-clean-eventual-consistency#6]
When I try to create a card, I get the following error:

![2021-09-09_203023](https://user-images.githubusercontent.com/12379287/132722142-4e0d1805-308b-45d8-b432-d11612646bb3.png)

![20202](https://user-images.githubusercontent.com/12379287/132723461-ebfbd908-4764-42a1-866b-ad78aa5de6b5.png)

![20201](https://user-images.githubusercontent.com/12379287/132723139-79328d53-c0c0-4218-b32f-0582068083bc.png)

**Comment by fals** [comment]
Hi thank you for reporting the issue. I'm going to look. This project is a template than a full working solution.

**Comment by fals** [comment]
@jamalkaksouri I think you had issues with the database. I made several changes in the project, I ran it locally and tested some endpoints, everything works as expected :).
